import { Activity, CircleCheck, Clock3, FileText, Gauge, Printer, RefreshCw } from 'lucide-react';
import { Link } from 'wouter';
import { clientText, Metric, PageIntro, Panel, PanelHeader, QuickLink, Tag, useClientDashboard, type ClientRequest } from './client-dashboard-shell';

function requestStatus(language: 'ar' | 'en', request: ClientRequest) {
  return language === 'ar' ? request.statusAr : request.statusEn;
}

function requestDate(value: string | Date, language: 'ar' | 'en') {
  const date = new Date(value);
  return new Intl.DateTimeFormat(language === 'ar' ? 'ar-SA' : 'en-US', { dateStyle: 'medium' }).format(date);
}

export function ClientOverviewPage() {
  const { language, profile, requests, isLoading, error, refresh } = useClientDashboard();
  const activeCount = requests.filter((request) => request.status !== 'completed').length;
  const latest = requests[0];
  return <div className="mx-auto max-w-[1480px]">
    <PageIntro code="CLIENT / 01 — OVERVIEW" title={clientText(language, `مرحباً، ${profile.name.split(' ')[0] || 'عميلنا'}`, `Welcome, ${profile.name.split(' ')[0] || 'client'}`)} description={clientText(language, 'هذه مساحة حقيقية لطلباتك الهندسية وحالة كل طلب محفوظ على حسابك.', 'A real workspace for your engineering requests and the status of every request saved to your account.')} action={<Tag tone="green">{clientText(language, 'حساب موثق', 'VERIFIED ACCOUNT')}</Tag>} />
    {Boolean(error) && <div className="mt-6 flex items-center justify-between gap-4 border border-destructive/40 bg-destructive/10 p-4 text-sm text-destructive-foreground"><span>{clientText(language, 'تعذر تحميل بيانات الحساب. حاول مرة أخرى.', 'We could not load your account data. Try again.')}</span><button type="button" onClick={() => void refresh()} className="inline-flex items-center gap-2 border border-destructive/40 px-3 py-2 font-code text-[9px]"><RefreshCw className="size-3" />RETRY</button></div>}
    <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="TOTAL REQUESTS" value={isLoading ? '—' : String(requests.length).padStart(2, '0')} note={clientText(language, 'كل الطلبات المحفوظة', 'All saved requests')} icon={FileText} /><Metric label="ACTIVE" value={isLoading ? '—' : String(activeCount).padStart(2, '0')} note={clientText(language, 'طلبات بانتظار إجراء', 'Requests still in progress')} icon={Activity} /><Metric label="LAST STATUS" value={isLoading ? '—' : latest ? latest.status.toUpperCase() : '—'} note={latest ? requestStatus(language, latest) : clientText(language, 'لا توجد طلبات', 'No requests yet')} icon={Gauge} /><Metric label="ACCOUNT" value={profile.company ? 'READY' : 'OPEN'} note={profile.company || clientText(language, 'أضف اسم الشركة من الإعدادات', 'Add your company in settings')} icon={CircleCheck} /></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.45fr_.8fr]">
      <Panel><PanelHeader eyebrow="REQUESTS / PERSISTED" title={clientText(language, 'طلباتك الأخيرة', 'Your recent requests')} action={<Link href="/client/printing" className="font-code text-[9px] text-primary hover:underline">{clientText(language, 'طلب جديد', 'NEW REQUEST')}</Link>} />{isLoading ? <div className="p-6 text-sm text-muted-foreground">{clientText(language, 'جارٍ تحميل بياناتك…', 'Loading your data…')}</div> : requests.length === 0 ? <div className="p-6"><p className="font-display text-xl font-bold">{clientText(language, 'لا توجد طلبات محفوظة بعد', 'No saved requests yet')}</p><p className="mt-2 text-sm leading-7 text-muted-foreground">{clientText(language, 'ابدأ بطلب طباعة ثلاثية الأبعاد، وسيظهر هنا مع مرجعه وحالته.', 'Start a 3D printing request and it will appear here with its reference and status.')}</p><Link href="/client/printing" className="mt-6 inline-flex h-11 items-center gap-2 bg-primary px-5 text-sm font-bold text-primary-foreground"><Printer className="size-4" />{clientText(language, 'ابدأ طلباً', 'Start a request')}</Link></div> : <div className="divide-y divide-border/70">{requests.map((request) => <div key={request.id} className="flex flex-col gap-4 px-5 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Tag tone={request.status === 'completed' ? 'green' : request.status === 'submitted' ? 'amber' : 'blue'}>{requestStatus(language, request)}</Tag><span className="font-code text-[9px] text-muted-foreground">{request.reference}</span></div><p className="mt-3 truncate font-display text-lg font-bold">{request.projectName}</p><p className="mt-1 text-xs text-muted-foreground">{request.material} · {request.quantity} {clientText(language, 'قطعة', 'units')} · {requestDate(request.createdAt, language)}</p></div><Link href="/client/printing" className="inline-flex shrink-0 items-center gap-2 text-sm font-semibold text-primary hover:underline">{clientText(language, 'عرض الطلبات', 'View requests')} <span aria-hidden>↗</span></Link></div>)}</div>}</Panel>
      <Panel><PanelHeader eyebrow="ACCESS / ACTIONS" title={clientText(language, 'اختصارات حقيقية', 'Useful shortcuts')} /><div className="grid gap-3 p-5 sm:p-6"><QuickLink href="/client/printing" code="PRINT / 01" title={clientText(language, 'طلب طباعة جديد', 'New print request')} description={clientText(language, 'أرسل المواصفات لفريق الهندسة', 'Send specifications to engineering')} icon={Printer} /><QuickLink href="/client/settings" code="ACCOUNT / 02" title={clientText(language, 'تحديث بيانات الحساب', 'Update account details')} description={clientText(language, 'الاسم والشركة واللغة', 'Name, company, and language')} icon={FileText} /></div></Panel>
    </div>
    <div className="mt-4 flex items-center gap-3 border border-primary/20 bg-primary/5 p-5 text-sm text-muted-foreground"><Clock3 className="size-4 shrink-0 text-primary" />{clientText(language, 'حالة الطلب تتغير فقط عندما يسجلها فريق AJ، ولا توجد مواعيد أو نسب تقدم افتراضية.', 'Request status changes only when AJ records it; there are no fabricated dates or progress percentages.')}</div>
  </div>;
}

export default ClientOverviewPage;