import type {
  DesignStage,
  Differentiator,
  HomeContent,
  Material,
  ServiceDetail,
  ServiceSummary,
  Stat,
} from "@workspace/api-zod";

export const stats: Stat[] = [
  { value: "06", labelAr: "خدمات هندسية متخصصة", labelEn: "Specialized services" },
  { value: "18", labelAr: "سنة خبرة صناعية", labelEn: "Years of experience" },
  { value: "04", labelAr: "مراحل اعتماد واضحة", labelEn: "Clear project stages" },
  { value: "24h", labelAr: "زمن الرد الأولي", labelEn: "Initial response time" },
];

export const designStages: DesignStage[] = [
  {
    number: 1,
    titleAr: "الاجتماع وفهم المتطلبات",
    titleEn: "Brief & meeting",
    descriptionAr: "تحليل الاحتياج وهدف الإنتاج والمساحة المتاحة.",
    descriptionEn: "Understanding the need, production target, and available footprint.",
  },
  {
    number: 2,
    titleAr: "المخطط الأولي",
    titleEn: "Concept sketch",
    descriptionAr: "تحويل الفكرة إلى تصور هندسي قابل للمراجعة.",
    descriptionEn: "Turning the idea into a reviewable engineering concept.",
  },
  {
    number: 3,
    titleAr: "النمذجة ثلاثية الأبعاد",
    titleEn: "3D modelling",
    descriptionAr: "بناء نموذج CAD تفصيلي للأجزاء والتجميعات.",
    descriptionEn: "Building a detailed CAD model of parts and assemblies.",
  },
  {
    number: 4,
    titleAr: "المحاكاة والاختبار",
    titleEn: "Simulation",
    descriptionAr: "تحليل الإجهاد والحركة والتداخل قبل التصنيع.",
    descriptionEn: "Testing stress, motion, and interference before fabrication.",
  },
  {
    number: 5,
    titleAr: "المخططات التنفيذية",
    titleEn: "Technical drawings",
    descriptionAr: "تسليم رسومات 2D وقائمة مكونات جاهزة للتصنيع.",
    descriptionEn: "Delivering production-ready 2D drawings and BOM files.",
  },
  {
    number: 6,
    titleAr: "المراجعة والتسليم",
    titleEn: "Revision & delivery",
    descriptionAr: "اعتماد العميل وتسليم الملفات النهائية المنظمة.",
    descriptionEn: "Client approval and an organized final file handover.",
  },
];

export const differentiators: Differentiator[] = [
  {
    titleAr: "حل هندسي متكامل",
    titleEn: "One engineering partner",
    descriptionAr: "من الفكرة والـ CAD إلى ملفات التصنيع والقطعة الوظيفية.",
    descriptionEn: "From the idea and CAD to manufacturing files and functional parts.",
  },
  {
    titleAr: "تقليل المخاطر قبل الإنتاج",
    titleEn: "Less risk before production",
    descriptionAr: "اختبر الحركة والملاءمة والخامة قبل الالتزام بتصنيع مكلف.",
    descriptionEn: "Validate motion, fit, and materials before costly production.",
  },
  {
    titleAr: "وضوح تقني يمكن الوثوق به",
    titleEn: "Technical clarity",
    descriptionAr: "مخرجات محددة وتفاوتات موثقة وتواصل مباشر مع المهندس.",
    descriptionEn: "Defined outputs, documented tolerances, and direct engineering communication.",
  },
];

export const homeContent: HomeContent = {
  stats,
  designStages,
  differentiators,
};

const serviceGalleries: Record<string, ServiceDetail["gallery"]> = {
  "packaging-filling-machines": [
    { image: "/media/why-we-2.png", titleAr: "محطة تعبئة سيرفو مخصصة", titleEn: "Custom servo filling station", descriptionAr: "تجهيز خط تعبئة مدمج مع تحكم دقيق في الجرعة والحركة.", descriptionEn: "A compact filling line with precise dosing and motion control." },
    { image: "/media/why-we-3.jpeg", titleAr: "وحدة فهرسة للعبوات", titleEn: "Container indexing unit", descriptionAr: "تصميم عملي يحافظ على ثبات المنتج أثناء الانتقال بين مراحل الخط.", descriptionEn: "A practical indexing system that keeps products stable between line stages." },
    { image: "/media/why-we-1.jpeg", titleAr: "مراجعة نموذج خط الإنتاج", titleEn: "Production-line model review", descriptionAr: "محاكاة المسار والمساحات قبل اعتماد التصنيع والتركيب.", descriptionEn: "Route and footprint simulation before fabrication and installation approval." },
  ],
  "conveyor-systems": [
    { image: "/media/why-we-2.png", titleAr: "ناقل وحدات صناعي", titleEn: "Industrial modular conveyor", descriptionAr: "مسار حركة مصمم ليتوافق مع مساحة التشغيل ونقاط التسليم.", descriptionEn: "A movement route designed around the operating footprint and handoff points." },
    { image: "/media/why-we-3.jpeg", titleAr: "ناقل حلزوني مدمج", titleEn: "Compact spiral conveyor", descriptionAr: "استغلال الارتفاع لتقليل المساحة وتحسين انتقال المنتج.", descriptionEn: "Vertical movement that saves floor space and improves product transfer." },
    { image: "/media/why-we-1.jpeg", titleAr: "هيكل ستانلس لخط تعبئة", titleEn: "Stainless frame for a filling line", descriptionAr: "هيكل قابل للصيانة ومجهز للبيئة الصناعية الرطبة.", descriptionEn: "A serviceable frame prepared for a demanding, wet industrial environment." },
  ],
  "cad-modeling-simulation": [
    { image: "/media/why-we-1.jpeg", titleAr: "تجميع CAD قابل للمراجعة", titleEn: "Review-ready CAD assembly", descriptionAr: "نموذج رقمي يوضح العلاقة بين الأجزاء قبل تصنيع النموذج الأولي.", descriptionEn: "A digital model clarifying part relationships before the first prototype." },
    { image: "/media/why-we-3.jpeg", titleAr: "محاكاة الحركة والتداخل", titleEn: "Motion and interference study", descriptionAr: "اختبار الحركة ونقاط التداخل لتقليل إعادة العمل في المصنع.", descriptionEn: "Motion and interference testing to reduce rework on the factory floor." },
    { image: "/media/why-we-2.png", titleAr: "حزمة رسومات للتصنيع", titleEn: "Production drawing package", descriptionAr: "رسومات منظمة وقائمة مكونات تساعد فريق التصنيع على البدء بثقة.", descriptionEn: "Organized drawings and a BOM that let the fabrication team start with confidence." },
  ],
  "reverse-engineering-upgrades": [
    { image: "/media/why-we-1.jpeg", titleAr: "إعادة بناء قطعة قديمة", titleEn: "Legacy part reconstruction", descriptionAr: "تحويل القياسات والعينة إلى نموذج جديد قابل للتصنيع.", descriptionEn: "Turning measurements and a sample into a manufacturable new model." },
    { image: "/media/why-we-2.png", titleAr: "ترقية آلية الحركة", titleEn: "Mechanism upgrade", descriptionAr: "تحسين الحركة والوصول والصيانة دون تغيير كامل للآلة.", descriptionEn: "Improving motion, access, and serviceability without replacing the whole machine." },
    { image: "/media/why-we-3.jpeg", titleAr: "فحص القطعة بعد التصنيع", titleEn: "Post-machining inspection", descriptionAr: "مراجعة الأبعاد والملاءمة قبل إعادة القطعة إلى خط الإنتاج.", descriptionEn: "Dimensional and fit review before returning the part to production." },
  ],
  "gears-pulleys": [
    { image: "/media/why-we-3.jpeg", titleAr: "طقم مسننات دقيق", titleEn: "Precision gear set", descriptionAr: "تفاوتات محسوبة لتعشيق هادئ وعمر تشغيل أطول.", descriptionEn: "Controlled tolerances for quiet meshing and longer service life." },
    { image: "/media/why-we-2.png", titleAr: "بكرة توقيت صناعية", titleEn: "Industrial timing pulley", descriptionAr: "قطعة مصممة حول الحمل، المسافة، وسرعة الحركة المطلوبة.", descriptionEn: "A pulley designed around the required load, distance, and speed." },
    { image: "/media/why-we-1.jpeg", titleAr: "مراجعة التصميم قبل التشغيل", titleEn: "Design review before machining", descriptionAr: "تأكيد الموديول والخلوص ونقاط التثبيت قبل تجهيز ملفات التشغيل.", descriptionEn: "Module, backlash, and mounting checks before preparing machining files." },
  ],
  "obsolete-spare-parts": [
    { image: "/media/why-we-3.jpeg", titleAr: "بديل قطعة غيار منقرضة", titleEn: "Replacement for a discontinued part", descriptionAr: "إعادة إنتاج قطعة لم تعد متاحة مع الحفاظ على الملاءمة الأصلية.", descriptionEn: "Reproducing an unavailable part while preserving the original fit." },
    { image: "/media/why-we-1.jpeg", titleAr: "التقاط أبعاد قطعة مكسورة", titleEn: "Broken-part dimensional capture", descriptionAr: "استخراج الأبعاد المهمة من العينة لتحديد سبب الفشل.", descriptionEn: "Capturing critical dimensions from a sample to understand the failure." },
    { image: "/media/why-we-2.png", titleAr: "اختبار الملاءمة على الآلة", titleEn: "Machine fit verification", descriptionAr: "تجربة البديل على النظام قبل التسليم النهائي.", descriptionEn: "Testing the replacement on the system before final handover." },
  ],
};

export const services: ServiceDetail[] = [
  {
    slug: "packaging-filling-machines",
    titleAr: "تصميم ماكينات التعبئة والتغليف",
    titleEn: "Packaging & filling machines",
    descriptionAr: "حلول مخصصة لخطوط السوائل والحبوب والتغليف الحراري والكرتوني.",
    descriptionEn: "Custom solutions for liquid, granular, thermal, and carton packaging lines.",
    category: "Machine design",
    duration: "3–6 weeks",
    accent: "cyan",
    gallery: serviceGalleries["packaging-filling-machines"],
    highlightsAr: [
      "نمذجة ثلاثية الأبعاد ومحاكاة الحركة قبل التصنيع",
      "أنظمة تعبئة دقيقة للسوائل والمواد الجافة",
      "تكامل PLC ومحركات السيرفو للتشغيل المستمر",
      "اختبار FAT وتركيب وتدريب فريق التشغيل",
    ],
    highlightsEn: [
      "3D CAD modelling and motion simulation before fabrication",
      "Precision dosing for liquids and dry materials",
      "PLC and servo integration for continuous duty",
      "FAT validation, installation, and operator training",
    ],
    workflowAr: [
      "تحليل المنتج والطاقة الإنتاجية والمساحة",
      "تقديم المخططات والنموذج والتكلفة الفنية",
      "اعتماد التصميم والبدء بدفعة 25%",
      "التصنيع والتجميع والاختبار التشغيلي",
      "التسليم والتركيب والتدريب",
    ],
    workflowEn: [
      "Evaluate product physics, throughput, and footprint",
      "Deliver drawings, model, and technical proposal",
      "Approve the design and begin with a 25% advance",
      "Fabricate, assemble, and run the acceptance test",
      "Install the system and train operators",
    ],
  },
  {
    slug: "conveyor-systems",
    titleAr: "تطوير وتصنيع أنظمة الناقلات",
    titleEn: "Conveyor systems",
    descriptionAr: "سيور شريطية ومفصلية وحلزونية مصممة لمسار الإنتاج والمساحة المتاحة.",
    descriptionEn: "Belt, modular, slat, and spiral conveyors designed around your production path.",
    category: "Machine design",
    duration: "2–5 weeks",
    accent: "blue",
    gallery: serviceGalleries["conveyor-systems"],
    highlightsAr: [
      "دراسة مسار الحركة وأبعاد الموقع",
      "حلول رأسية وحلزونية لاستغلال الارتفاع",
      "هياكل فولاذية أو ستانلس ستيل للاستخدام الشاق",
      "اختبار الأحمال والتكامل مع خط الإنتاج",
    ],
    highlightsEn: [
      "Factory route and footprint analysis",
      "Vertical and spiral solutions that use available height",
      "Steel or stainless structures for demanding duty",
      "Load testing and production-line integration",
    ],
    workflowAr: [
      "معاينة الموقع وزوايا الحركة",
      "نمذجة المسار وحساب الأحمال",
      "اعتماد التصميم والمواد",
      "تصنيع الهيكل وتركيب أجزاء الحركة",
      "الموازنة والتركيب والدعم الميداني",
    ],
    workflowEn: [
      "Inspect the site and movement angles",
      "Model the route and calculate moving loads",
      "Approve the design and materials",
      "Fabricate the frame and mount drive components",
      "Balance the line and provide field setup",
    ],
  },
  {
    slug: "cad-modeling-simulation",
    titleAr: "النمذجة ثلاثية الأبعاد والمحاكاة",
    titleEn: "3D CAD & simulation",
    descriptionAr: "تصميم الماكينات واختبار الإجهاد وتدفق المواد قبل التصنيع الفعلي.",
    descriptionEn: "Digital machine design, stress analysis, and material-flow testing before fabrication.",
    category: "Digital engineering",
    duration: "1–2 weeks",
    accent: "violet",
    gallery: serviceGalleries["cad-modeling-simulation"],
    highlightsAr: [
      "نماذج CAD دقيقة للأجزاء والتجميعات",
      "تحليل إجهاد واختبار متانة الأحمال",
      "محاكاة الحركة وتدفق المنتج",
      "تسليم رسومات 2D وBOM للتصنيع",
    ],
    highlightsEn: [
      "Accurate CAD models for parts and assemblies",
      "FEA stress analysis for load and durability",
      "Motion and product-flow simulation",
      "2D drawings and BOM files for production",
    ],
    workflowAr: [
      "تحليل المدخلات والأبعاد والآلية المطلوبة",
      "بناء النموذج وإجراء المحاكاة",
      "اعتماد التصميم والدفعة الأولى",
      "تجهيز المخططات وقائمة المكونات",
      "تسليم حزمة التصميم النهائية",
    ],
    workflowEn: [
      "Review dimensions, inputs, and mechanism goals",
      "Build the model and run simulations",
      "Approve the design and initial phase",
      "Prepare production drawings and component lists",
      "Hand over the final CAD package",
    ],
  },
  {
    slug: "reverse-engineering-upgrades",
    titleAr: "الهندسة العكسية وتطوير الآلات",
    titleEn: "Reverse engineering & upgrades",
    descriptionAr: "إعادة بناء القطع القديمة وتحديث الآليات لرفع الكفاءة وتقليل الأعطال.",
    descriptionEn: "Reconstructing legacy parts and upgrading mechanisms to improve efficiency and uptime.",
    category: "Machine improvement",
    duration: "1–3 weeks",
    accent: "amber",
    gallery: serviceGalleries["reverse-engineering-upgrades"],
    highlightsAr: [
      "رفع أبعاد القطع وإعادة نمذجتها بدقة",
      "تصنيع بدائل للأجزاء النادرة أو المتوقفة",
      "تحديث الميكانيزم ونظام التحكم",
      "اختبار القطعة على النظام قبل التسليم",
    ],
    highlightsEn: [
      "Precision measurement and CAD reconstruction",
      "Replacement parts for rare or discontinued components",
      "Mechanism and controls upgrades",
      "Fit and operational testing before delivery",
    ],
    workflowAr: [
      "فحص الآلة أو القطعة وتحديد فرص التطوير",
      "رفع الأبعاد وإنشاء النموذج المحدث",
      "اعتماد المخططات والدفعة الأولى",
      "تشغيل القطع وتجميعها على النظام",
      "التجربة والتسليم والتعديل عند الحاجة",
    ],
    workflowEn: [
      "Inspect the machine or part and identify improvements",
      "Measure the component and build the updated model",
      "Approve drawings and begin the first phase",
      "Machine the parts and integrate them",
      "Trial, hand over, and tune where needed",
    ],
  },
  {
    slug: "gears-pulleys",
    titleAr: "تصنيع المسننات والبكرات",
    titleEn: "Gears & pulleys",
    descriptionAr: "تصميم وتصنيع المسننات والبكرات مع ضبط التفاوتات للحركة السلسة.",
    descriptionEn: "Precision gears and pulleys with tolerance control for smooth, quiet motion.",
    category: "Precision parts",
    duration: "3 days–2 weeks",
    accent: "green",
    gallery: serviceGalleries["gears-pulleys"],
    highlightsAr: [
      "مسننات مستقيمة وحلزونية ومخروطية ودودية",
      "بكرات توقيت وبكرات سيور بدقة عالية",
      "حساب الخلوص والتفاوتات لتقليل الاحتكاك",
      "اختبار التعشيق وفحص القياسات قبل التسليم",
    ],
    highlightsEn: [
      "Spur, helical, bevel, and worm gears",
      "High-precision timing and V-belt pulleys",
      "Backlash and tolerance control",
      "Mesh testing and dimensional inspection",
    ],
    workflowAr: [
      "قياس العينة وتحديد الموديول وعدد الأسنان",
      "نمذجة القطعة وتجهيز ملفات التشغيل",
      "اختيار الخامة واعتماد المخطط",
      "التفريز والمعالجة وضبط القياسات",
      "فحص التعشيق وتسليم العمل",
    ],
    workflowEn: [
      "Measure the sample and define module and tooth count",
      "Model the part and prepare machining paths",
      "Select the material and approve the drawing",
      "Machine, finish, and verify dimensions",
      "Test the mesh and deliver the part",
    ],
  },
  {
    slug: "obsolete-spare-parts",
    titleAr: "بدائل قطع الغيار المنقرضة",
    titleEn: "Obsolete spare parts",
    descriptionAr: "إعادة تصميم وإنتاج القطع المكسورة أو غير المتوفرة للآلات القديمة.",
    descriptionEn: "Redesigning and manufacturing broken or discontinued parts for legacy machinery.",
    category: "Precision parts",
    duration: "3 days–2 weeks",
    accent: "rose",
    gallery: serviceGalleries["obsolete-spare-parts"],
    highlightsAr: [
      "إعادة بناء القطع المتآكلة أو المكسورة",
      "بدائل للآلات التي توقف دعمها من المصنع",
      "اختيار المعادن أو البوليمرات المناسبة",
      "تصنيع CNC أو طباعة هندسية عالية القوة",
    ],
    highlightsEn: [
      "Reconstruction of worn or broken components",
      "Alternatives for unsupported legacy machinery",
      "Material selection for the work environment",
      "CNC machining or high-strength technical printing",
    ],
    workflowAr: [
      "استلام العينة أو أخذ القياسات في الموقع",
      "إعادة التصميم ومعالجة مناطق الفشل",
      "اعتماد الخامة والمخطط",
      "التصنيع أو الطباعة والمعالجة",
      "اختبار الملاءمة والتسليم",
    ],
    workflowEn: [
      "Receive the sample or measure on site",
      "Re-engineer the geometry and failure points",
      "Approve the material and drawing",
      "Fabricate or print and finish the part",
      "Verify fit and hand over the replacement",
    ],
  },
];

export const materials: Material[] = [
  {
    id: "pla-tough",
    name: "PLA+ / Tough PLA",
    applicationAr: "النماذج الأولية والحوامل والأغطية منخفضة الإجهاد",
    applicationEn: "Prototypes, brackets, and low-stress enclosures",
    characteristicsAr: "صلابة ودقة أبعاد ممتازة ومقاومة إجهاد محسّنة.",
    characteristicsEn: "Rigid with excellent dimensional accuracy and improved stress resistance.",
    examplesAr: "نماذج توضيحية، حوامل ميكانيكية، وأغطية الأجهزة.",
    examplesEn: "Visual models, mechanical brackets, and equipment enclosures.",
    pricePerGram: 0.08,
    leadDays: 3,
  },
  {
    id: "petg",
    name: "PETG",
    applicationAr: "قطع السيور وخطوط التعبئة الملامسة للسوائل",
    applicationEn: "Conveyor parts and filling-line components near liquids",
    characteristicsAr: "مقاومة كيميائية وللزيوت مع متانة ومرونة ممتازة.",
    characteristicsEn: "Chemical and oil resistance with strong, practical toughness.",
    examplesAr: "حوامل خارجية، وصلات سريعة، وحاويات مانعة للتسرب.",
    examplesEn: "Outdoor brackets, snap-fits, and water-tight containers.",
    pricePerGram: 0.11,
    leadDays: 4,
  },
  {
    id: "abs-asa",
    name: "ABS / ASA",
    applicationAr: "أجزاء الآلات الخارجية والأغطية الواقية",
    applicationEn: "External machine parts and protective covers",
    characteristicsAr: "تحمل حراري ممتاز ومقاومة عالية للصدمات والظروف الجوية.",
    characteristicsEn: "Strong heat and impact resistance for demanding environments.",
    examplesAr: "أغطية الحركات الميكانيكية وهياكل الاستخدام الخارجي.",
    examplesEn: "Motion guards and components for outdoor use.",
    pricePerGram: 0.14,
    leadDays: 5,
  },
  {
    id: "nylon-cf",
    name: "Nylon / CF",
    applicationAr: "المسننات والبكرات والمجاري الميكانيكية",
    applicationEn: "Industrial gears, pulleys, and mechanical guides",
    characteristicsAr: "صلابة فائقة ومقاومة للتآكل والاحتكاك.",
    characteristicsEn: "Very high stiffness with excellent wear and abrasion resistance.",
    examplesAr: "مسننات صناعية مباشرة وبكرات ومجاري الحركة.",
    examplesEn: "Industrial spur gears, pulleys, and motion guides.",
    pricePerGram: 0.2,
    leadDays: 7,
  },
  {
    id: "sla-resin",
    name: "SLA Resin",
    applicationAr: "الدقة الفائقة والأسطح الملساء والنماذج الصغيرة",
    applicationEn: "Ultra-precise small parts and smooth surface models",
    characteristicsAr: "تفاصيل دقيقة جداً وتشطيب سطحي أملس وتفاوتات ضيقة.",
    characteristicsEn: "Fine details, smooth surface finish, and tight tolerances.",
    examplesAr: "نماذج المسننات الصغيرة والقوالب والنماذج البصرية.",
    examplesEn: "Small gear prototypes, master molds, and visual models.",
    pricePerGram: 0.24,
    leadDays: 6,
  },
];